module.exports = {
  UPDATE_INPUT: "UPDATE_INPUT",
  SUBMIT_SEARCH: "SUBMIT_SEARCH",
  SUBMIT_SUCCESS: "SUBMIT_SUCCESS",
  SUBMIT_FAILURE: "SUBMIT_FAILURE",
  FETCH_VENUE_DATA: "FETCH_VENUE_DATA",
  VENUE_SUCCESS: "VENUE_SUCCESS",
  VENUE_ERROR: "VENUE_ERROR",
  FETCH_IS_GOING: "FETCH_IS_GOING",
  IS_GOING_SUCCESS: "IS_GOING_SUCCESS",
  IS_GOING_ERROR: "IS_GOING_ERROR"
};
